version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: 'mysql:33061'
    platform: linux/x86_64
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234567890
      - MYSQL_USER=commerce
      - MYSQL_PASSWORD=1234567890
      - MYSQL_DATABASE=commerce
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
